import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { generateVanitySalt } from "@/lib/vanity";
import { ethers } from "ethers";
import { rateLimitMiddleware } from "@/lib/rate-limit";

// Load compiled LaunchpadToken bytecode for local CREATE2 computation.
// This file is generated by `npx hardhat compile` and should be copied/symlinked
// into the Next.js source tree, or loaded via path alias.
let TOKEN_CREATION_CODE: string | undefined;
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const artifact = require("@/artifacts/contracts/LaunchpadToken.sol/LaunchpadToken.json");
  TOKEN_CREATION_CODE = artifact.bytecode;
} catch {
  // Artifact not available at build time — will be checked at runtime
}

/**
 * POST /api/launch/precompute
 *
 * Generate vanity salt + predict contract address BEFORE user signs the deploy tx.
 * Uses local CREATE2 computation (no RPC calls per attempt) for ~1000x speed improvement.
 *
 * Flow:
 *   1. User submits form data
 *   2. Backend brute-forces salt locally until address ends with suffix
 *   3. Return salt + predicted address to user
 *   4. User signs createLaunch() tx with the salt + launchDate
 *   5. Contract deploys at predicted address
 */
export async function POST(request: NextRequest) {
  try {
    // Rate limit: 10 requests per minute per IP (expensive operation)
    const rateLimited = await rateLimitMiddleware(request, 10, 60_000);
    if (rateLimited) return rateLimited;

    const body = await request.json();
    const {
      walletAddress,
      tokenName,
      tokenSymbol,
      totalSupply,
      decimals = 18,
      description,
      logoUrl,
      websiteUrl,
      socialLinks,
      targetChain = "ethereum",
      basePrice,
      graduationCap,
      launchDate,
      maxLeveragePercent = 50,
      suffix = "911",
    } = body;

    // Validation
    if (
      !walletAddress ||
      !tokenName ||
      !tokenSymbol ||
      !totalSupply ||
      !basePrice ||
      !graduationCap ||
      !launchDate
    ) {
      return NextResponse.json(
        { success: false, error: "Missing required fields" },
        { status: 400 }
      );
    }

    if (Number(basePrice) <= 0 || Number(totalSupply) <= 0) {
      return NextResponse.json(
        { success: false, error: "Invalid base price or total supply" },
        { status: 400 }
      );
    }

    // Get or create user
    let user = await prisma.user.findUnique({
      where: { walletAddress: walletAddress.toLowerCase() },
    });

    if (!user) {
      user = await prisma.user.create({
        data: {
          walletAddress: walletAddress.toLowerCase(),
          balance: 0,
        },
      });
    }

    // Get factory address
    const factoryAddress = process.env.LAUNCHPAD_FACTORY_ADDRESS;
    if (
      !factoryAddress ||
      factoryAddress === "0x0000000000000000000000000000000000000000"
    ) {
      return NextResponse.json(
        {
          success: false,
          error: "Factory address not configured. Set LAUNCHPAD_FACTORY_ADDRESS in .env",
        },
        { status: 500 }
      );
    }

    // Get platform wallet
    const platformWallet = process.env.PLATFORM_WALLET_ADDRESS;
    if (!platformWallet) {
      return NextResponse.json(
        {
          success: false,
          error: "Platform wallet not configured. Set PLATFORM_WALLET_ADDRESS in .env",
        },
        { status: 500 }
      );
    }

    // Check that compiled bytecode is available
    if (!TOKEN_CREATION_CODE) {
      return NextResponse.json(
        {
          success: false,
          error: "LaunchpadToken artifact not found. Run `npx hardhat compile` first.",
        },
        { status: 500 }
      );
    }

    // Compute slope and validate
    const totalSupplyNum = Number(totalSupply);
    const basePriceNum = Number(basePrice);
    const capNum = Number(graduationCap);
    const slope =
      (2 * (capNum - basePriceNum * totalSupplyNum)) /
      (totalSupplyNum * totalSupplyNum);

    if (slope <= 0) {
      return NextResponse.json(
        {
          success: false,
          error:
            "Invalid parameters: graduation cap too low for the given supply and base price. Slope would be <= 0.",
        },
        { status: 400 }
      );
    }

    // Convert scientific notation to decimal strings for ethers.parseEther
    const toDecimal = (v: number): string => {
      // For very small numbers, use BigInt wei conversion
      if (v < 1) {
        const wei = BigInt(Math.round(v * 1e18));
        return ethers.formatEther(wei);
      }
      return v.toFixed(18).replace(/\.?0+$/, "");
    };

    const basePriceWei = ethers.parseEther(toDecimal(basePriceNum));
    const slopeWei = ethers.parseEther(toDecimal(slope));
    const graduationCapWei = ethers.parseEther(graduationCap.toString());

    // Generate vanity salt (local compute — no RPC calls)
    const startTime = Date.now();
    let vanity;
    const launchDateTs = BigInt(
      Math.floor(new Date(launchDate).getTime() / 1000)
    );
    try {
      vanity = await generateVanitySalt({
        factoryAddress,
        name: tokenName,
        symbol: tokenSymbol,
        totalSupply: ethers.parseEther(totalSupply.toString()),
        platformWallet,
        creator: walletAddress,
        launchDate: launchDateTs,
        suffix,
        maxAttempts: 500_000,
        tokenCreationCode: TOKEN_CREATION_CODE,
      });
    } catch (err) {
      return NextResponse.json(
        {
          success: false,
          error: `Vanity generation failed: ${err instanceof Error ? err.message : "Unknown error"}`,
        },
        { status: 500 }
      );
    }
    const elapsedMs = Date.now() - startTime;

    // Save launch record with precomputed data
    const launch = await prisma.tokenLaunch.create({
      data: {
        creatorId: user.id,
        tokenName,
        tokenSymbol: tokenSymbol.toUpperCase(),
        decimals,
        totalSupply: Number(totalSupply),
        description: description || null,
        logoUrl: logoUrl || null,
        websiteUrl: websiteUrl || null,
        socialLinks: socialLinks || null,
        basePrice: Number(basePrice),
        graduationCap: Number(graduationCap),
        launchDate: new Date(launchDate),
        maxLeveragePercent: Math.min(50, Math.max(10, maxLeveragePercent)),
        vanitySuffix: suffix,
        contractAddress: vanity.predictedAddress,
        network: targetChain,
        status: "awaiting_deploy",
        deployFeeNative: 0,
        deployFeePaid: false,
      },
    });

    return NextResponse.json({
      success: true,
      data: {
        launchId: launch.id,
        salt: vanity.salt,
        predictedAddress: vanity.predictedAddress,
        suffix,
        attempts: vanity.attempts,
        elapsedMs,
        factoryAddress,
        deployParams: {
          salt: vanity.salt,
          name: tokenName,
          symbol: tokenSymbol,
          totalSupply: ethers.parseEther(totalSupply.toString()).toString(),
          basePrice: basePriceWei.toString(),
          slope: slopeWei.toString(),
          graduationCap: graduationCapWei.toString(),
          launchDate: launchDateTs.toString(),
        },
      },
    });
  } catch (error) {
    console.error("Error precomputing launch:", error);
    return NextResponse.json(
      { success: false, error: "Internal server error" },
      { status: 500 }
    );
  }
}
